 debian@debian12:~/Downloads/NETSTAT$ pip install scapy
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
debian@debian12:~/Downloads/NETSTAT$ 
debian@debian12:~/Downloads/NETSTAT$ su -
Password: 
root@debian12:~# pip install scapy
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
root@debian12:~# sudo apt update
sudo apt install python3-venv python3-pip
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease  
Hit:3 http://security.debian.org/debian-security bookworm-security InRelease
Hit:4 https://packages.microsoft.com/repos/code stable InRelease
Reading package lists... Done                           
Building dependency tree... Done
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (23.0.1+dfsg-1).
The following additional packages will be installed:
  python3-pip-whl python3-setuptools-whl python3.11-venv
The following NEW packages will be installed:
  python3-pip-whl python3-setuptools-whl python3-venv python3.11-venv
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 2,836 kB of archives.
After this operation, 3,170 kB of additional disk space will be used.
Do you want to continue? [Y/n] y 
Get:1 http://deb.debian.org/debian bookworm/main amd64 python3-pip-whl all 23.0.1+dfsg-1 [1,717 kB]
Get:2 http://security.debian.org/debian-security bookworm-security/main amd64 python3.11-venv amd64 3.11.2-6+deb12u3 [5,896 B]
Get:3 http://deb.debian.org/debian bookworm/main amd64 python3-setuptools-whl all 66.1.1-1 [1,111 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 python3-venv amd64 3.11.2-1+b1 [1,200 B]
Fetched 2,836 kB in 1s (4,103 kB/s)      
Selecting previously unselected package python3-pip-whl.
(Reading database ... 214997 files and directories currently installed.)
Preparing to unpack .../python3-pip-whl_23.0.1+dfsg-1_all.deb ...
Unpacking python3-pip-whl (23.0.1+dfsg-1) ...
Selecting previously unselected package python3-setuptools-whl.
Preparing to unpack .../python3-setuptools-whl_66.1.1-1_all.deb ...
Unpacking python3-setuptools-whl (66.1.1-1) ...
Selecting previously unselected package python3.11-venv.
Preparing to unpack .../python3.11-venv_3.11.2-6+deb12u3_amd64.deb ...
Unpacking python3.11-venv (3.11.2-6+deb12u3) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../python3-venv_3.11.2-1+b1_amd64.deb ...
Unpacking python3-venv (3.11.2-1+b1) ...
Setting up python3-setuptools-whl (66.1.1-1) ...
Setting up python3-pip-whl (23.0.1+dfsg-1) ...
Setting up python3.11-venv (3.11.2-6+deb12u3) ...
Setting up python3-venv (3.11.2-1+b1) ...
root@debian12:~# mkdir ~/my_udp_monitor
cd ~/my_udp_monitor
python3 -m venv venv
root@debian12:~/my_udp_monitor# source venv/bin/activate
(venv) root@debian12:~/my_udp_monitor# pip install scapy
Collecting scapy
  Downloading scapy-2.6.0-py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 2.6 MB/s eta 0:00:00
Installing collected packages: scapy
Successfully installed scapy-2.6.0
(venv) root@debian12:~/my_udp_monitor# sudo apt install python3-scapy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  blt fonts-lyx ipython3 isympy-common isympy3 libboost-dev libboost1.74-dev
  libimagequant0 libjs-jquery-ui liblbfgsb0 libopenblas-dev libopenblas-pthread-dev
  libopenblas0 libopenblas0-pthread libpython3-all-dev libqhull-r8.0 libraqm0 libtcl8.6
  libtk8.6 libxsimd-dev python-matplotlib-data python3-all python3-all-dev
  python3-appdirs python3-asttokens python3-attr python3-backcall python3-beniget
  python3-bs4 python3-contourpy python3-cycler python3-decorator python3-executing
  python3-fonttools python3-fs python3-gast python3-html5lib python3-ipython python3-jedi
  python3-kiwisolver python3-lxml python3-lz4 python3-matplotlib
  python3-matplotlib-inline python3-mpmath python3-numpy python3-olefile
  python3-packaging python3-parso python3-pexpect python3-pickleshare python3-pil
  python3-pil.imagetk python3-prompt-toolkit python3-ptyprocess python3-pure-eval
  python3-pygments python3-pythran python3-scipy python3-soupsieve python3-stack-data
  python3-sympy python3-tk python3-traitlets python3-tz python3-ufolib2 python3-wcwidth
  python3-webencodings tk8.6-blt2.5 unicode-data
Suggested packages:
  blt-demo libboost-doc libboost1.74-doc libboost-atomic1.74-dev libboost-chrono1.74-dev
  libboost-container1.74-dev libboost-context1.74-dev libboost-contract1.74-dev
  libboost-coroutine1.74-dev libboost-date-time1.74-dev libboost-exception1.74-dev
  libboost-fiber1.74-dev libboost-filesystem1.74-dev libboost-graph1.74-dev
  libboost-graph-parallel1.74-dev libboost-iostreams1.74-dev libboost-locale1.74-dev
  libboost-log1.74-dev libboost-math1.74-dev libboost-mpi1.74-dev
  libboost-mpi-python1.74-dev libboost-numpy1.74-dev libboost-program-options1.74-dev
  libboost-python1.74-dev libboost-random1.74-dev libboost-regex1.74-dev
  libboost-serialization1.74-dev libboost-stacktrace1.74-dev libboost-system1.74-dev
  libboost-test1.74-dev libboost-thread1.74-dev libboost-timer1.74-dev
  libboost-type-erasure1.74-dev libboost-wave1.74-dev libboost1.74-tools-dev
  libmpfrc++-dev libntl-dev libboost-nowide1.74-dev libjs-jquery-ui-docs tcl8.6 tk8.6
  libxsimd-doc python-attr-doc python-cycler-doc python3-genshi python-ipython-doc
  python-lxml-doc cm-super-minimal dvipng fonts-staypuft inkscape python3-cairocffi
  python3-gobject python3-pyqt5 python3-sip python3-tornado texlive-extra-utils
  texlive-latex-extra python-mpmath-doc python3-gmpy2 gfortran python3-pytest
  python-pexpect-doc python-pil-doc python-pygments-doc ttf-bitstream-vera graphviz
  python-scapy-doc python3-pyx sox tcpreplay python-scipy-doc texlive-fonts-extra
  python-sympy-doc tix python3-tk-dbg
The following NEW packages will be installed:
  blt fonts-lyx ipython3 isympy-common isympy3 libboost-dev libboost1.74-dev
  libimagequant0 libjs-jquery-ui liblbfgsb0 libopenblas-dev libopenblas-pthread-dev
  libopenblas0 libopenblas0-pthread libpython3-all-dev libqhull-r8.0 libraqm0 libtcl8.6
  libtk8.6 libxsimd-dev python-matplotlib-data python3-all python3-all-dev
  python3-appdirs python3-asttokens python3-attr python3-backcall python3-beniget
  python3-bs4 python3-contourpy python3-cycler python3-decorator python3-executing
  python3-fonttools python3-fs python3-gast python3-html5lib python3-ipython python3-jedi
  python3-kiwisolver python3-lxml python3-lz4 python3-matplotlib
  python3-matplotlib-inline python3-mpmath python3-numpy python3-olefile
  python3-packaging python3-parso python3-pexpect python3-pickleshare python3-pil
  python3-pil.imagetk python3-prompt-toolkit python3-ptyprocess python3-pure-eval
  python3-pygments python3-pythran python3-scapy python3-scipy python3-soupsieve
  python3-stack-data python3-sympy python3-tk python3-traitlets python3-tz
  python3-ufolib2 python3-wcwidth python3-webencodings tk8.6-blt2.5 unicode-data
0 upgraded, 71 newly installed, 0 to remove and 3 not upgraded.
Need to get 75.1 MB of archives.
After this operation, 496 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian bookworm/main amd64 libtcl8.6 amd64 8.6.13+dfsg-2 [1,035 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 libtk8.6 amd64 8.6.13-2 [781 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 tk8.6-blt2.5 amd64 2.5.3+dfsg-4.1 [593 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 blt amd64 2.5.3+dfsg-4.1 [14.9 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 fonts-lyx all 2.3.7-1 [186 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 python3-backcall all 0.2.0-4 [12.1 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 python3-decorator all 5.1.1-3 [14.9 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 python3-parso all 0.8.3-1 [67.4 kB]
Get:9 http://deb.debian.org/debian bookworm/main amd64 python3-jedi all 0.18.2-1 [689 kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 python3-traitlets all 5.5.0-1 [92.4 kB]
Get:11 http://deb.debian.org/debian bookworm/main amd64 python3-matplotlib-inline all 0.1.6-2 [8,652 B]
Get:12 http://deb.debian.org/debian bookworm/main amd64 python3-ptyprocess all 0.7.0-5 [14.7 kB]
Get:13 http://deb.debian.org/debian bookworm/main amd64 python3-pexpect all 4.8.0-4 [52.9 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 python3-pickleshare all 0.7.5-5 [7,600 B]
Get:15 http://deb.debian.org/debian bookworm/main amd64 python3-wcwidth all 0.2.5+dfsg1-1.1 [21.4 kB]
Get:16 http://deb.debian.org/debian bookworm/main amd64 python3-prompt-toolkit all 3.0.36-2 [276 kB]
Get:17 http://deb.debian.org/debian bookworm/main amd64 python3-pygments all 2.14.0+dfsg-1 [783 kB]
Get:18 http://deb.debian.org/debian bookworm/main amd64 python3-asttokens all 2.2.1-1 [19.8 kB]
Get:19 http://deb.debian.org/debian bookworm/main amd64 python3-executing all 1.2.0-2 [22.6 kB]
Get:20 http://deb.debian.org/debian bookworm/main amd64 python3-pure-eval all 0.2.2-1 [11.2 kB]
Get:21 http://deb.debian.org/debian bookworm/main amd64 python3-stack-data all 0.6.2-3 [21.8 kB]
Get:22 http://deb.debian.org/debian bookworm/main amd64 python3-ipython all 8.5.0-4 [517 kB]
Get:23 http://deb.debian.org/debian bookworm/main amd64 ipython3 all 8.5.0-4 [22.7 kB]
Get:24 http://deb.debian.org/debian bookworm/main amd64 isympy-common all 1.11.1-1 [233 kB]
Get:25 http://deb.debian.org/debian bookworm/main amd64 python3-mpmath all 1.2.1-2 [418 kB]
Get:26 http://deb.debian.org/debian bookworm/main amd64 python3-sympy all 1.11.1-1 [4,358 kB]
Get:27 http://deb.debian.org/debian bookworm/main amd64 isympy3 all 1.11.1-1 [5,524 B]
Get:28 http://deb.debian.org/debian bookworm/main amd64 libboost1.74-dev amd64 1.74.0+ds1-21 [9,508 kB]
Get:29 http://deb.debian.org/debian bookworm/main amd64 libboost-dev amd64 1.74.0.3 [4,548 B]
Get:30 http://deb.debian.org/debian bookworm/main amd64 libimagequant0 amd64 2.17.0-1 [32.5 kB]
Get:31 http://deb.debian.org/debian bookworm/main amd64 libjs-jquery-ui all 1.13.2+dfsg-1 [250 kB]
Get:32 http://deb.debian.org/debian bookworm/main amd64 libopenblas0-pthread amd64 0.3.21+ds-4 [6,709 kB]
Get:33 http://deb.debian.org/debian bookworm/main amd64 liblbfgsb0 amd64 3.0+dfsg.4-1 [28.9 kB]
Get:34 http://deb.debian.org/debian bookworm/main amd64 libopenblas0 amd64 0.3.21+ds-4 [32.6 kB]
Get:35 http://deb.debian.org/debian bookworm/main amd64 libopenblas-pthread-dev amd64 0.3.21+ds-4 [4,971 kB]
Get:36 http://deb.debian.org/debian bookworm/main amd64 libopenblas-dev amd64 0.3.21+ds-4 [44.9 kB]
Get:37 http://deb.debian.org/debian bookworm/main amd64 libpython3-all-dev amd64 3.11.2-1+b1 [1,068 B]
Get:38 http://deb.debian.org/debian bookworm/main amd64 libqhull-r8.0 amd64 2020.2-5 [248 kB]
Get:39 http://deb.debian.org/debian bookworm/main amd64 libraqm0 amd64 0.7.0-4.1 [10.6 kB]
Get:40 http://deb.debian.org/debian bookworm/main amd64 libxsimd-dev amd64 8.1.0-7 [88.8 kB]
Get:41 http://deb.debian.org/debian bookworm/main amd64 python-matplotlib-data all 3.6.3-1 [2,744 kB]
Get:42 http://deb.debian.org/debian bookworm/main amd64 python3-all amd64 3.11.2-1+b1 [1,056 B]
Get:43 http://deb.debian.org/debian bookworm/main amd64 python3-all-dev amd64 3.11.2-1+b1 [1,072 B]
Get:44 http://deb.debian.org/debian bookworm/main amd64 python3-appdirs all 1.4.4-3 [13.0 kB]
Get:45 http://deb.debian.org/debian bookworm/main amd64 python3-attr all 22.2.0-1 [65.4 kB]
Get:46 http://deb.debian.org/debian bookworm/main amd64 python3-gast all 0.5.2-2 [9,364 B]
Get:47 http://deb.debian.org/debian bookworm/main amd64 python3-beniget all 0.4.1-3 [9,920 B]
Get:48 http://deb.debian.org/debian bookworm/main amd64 python3-soupsieve all 2.3.2-1 [38.8 kB]
Get:49 http://deb.debian.org/debian bookworm/main amd64 python3-bs4 all 4.11.2-2 [121 kB] 
Get:50 http://deb.debian.org/debian bookworm/main amd64 python3-numpy amd64 1:1.24.2-1+deb12u1 [4,960 kB]
Get:51 http://deb.debian.org/debian bookworm/main amd64 python3-contourpy amd64 1.0.7-1+b1 [176 kB]
Get:52 http://deb.debian.org/debian bookworm/main amd64 python3-cycler all 0.11.0-1 [8,020 B]
Get:53 http://deb.debian.org/debian bookworm/main amd64 python3-pythran amd64 0.11.0+ds-7 [427 kB]
Get:54 http://deb.debian.org/debian bookworm/main amd64 python3-scipy amd64 1.10.1-2 [15.2 MB]
Get:55 http://deb.debian.org/debian bookworm/main amd64 python3-ufolib2 all 0.14.0+dfsg1-1 [34.3 kB]
Get:56 http://deb.debian.org/debian bookworm/main amd64 python3-tz all 2022.7.1-4 [30.1 kB]
Get:57 http://deb.debian.org/debian bookworm/main amd64 python3-fs all 2.4.16-2 [95.2 kB] 
Get:58 http://deb.debian.org/debian bookworm/main amd64 python3-lxml amd64 4.9.2-1+b1 [1,194 kB]
Get:59 http://deb.debian.org/debian bookworm/main amd64 python3-lz4 amd64 4.0.2+dfsg-1+b2 [25.0 kB]
Get:60 http://deb.debian.org/debian bookworm/main amd64 unicode-data all 15.0.0-1 [7,984 kB]
Get:61 http://deb.debian.org/debian bookworm/main amd64 python3-fonttools amd64 4.38.0-1+b1 [1,012 kB]
Get:62 http://deb.debian.org/debian bookworm/main amd64 python3-webencodings all 0.5.1-5 [11.1 kB]
Get:63 http://deb.debian.org/debian bookworm/main amd64 python3-html5lib all 1.1-3 [93.0 kB]
Get:64 http://deb.debian.org/debian bookworm/main amd64 python3-kiwisolver amd64 1.4.4-1+b1 [60.1 kB]
Get:65 http://deb.debian.org/debian bookworm/main amd64 python3-pil amd64 9.4.0-1.1+deb12u1 [472 kB]
Get:66 http://deb.debian.org/debian bookworm/main amd64 python3-tk amd64 3.11.2-3 [98.3 kB]
Get:67 http://deb.debian.org/debian bookworm/main amd64 python3-pil.imagetk amd64 9.4.0-1.1+deb12u1 [74.2 kB]
Get:68 http://deb.debian.org/debian bookworm/main amd64 python3-packaging all 23.0-1 [32.5 kB]
Get:69 http://deb.debian.org/debian bookworm/main amd64 python3-matplotlib amd64 3.6.3-1+b1 [6,921 kB]
Get:70 http://deb.debian.org/debian bookworm/main amd64 python3-olefile all 0.46-3 [36.1 kB]
Get:71 http://deb.debian.org/debian bookworm/main amd64 python3-scapy all 2.5.0+dfsg-2 [959 kB]
Fetched 75.1 MB in 14s (5,268 kB/s)                                                       
Extracting templates from packages: 100%
Selecting previously unselected package libtcl8.6:amd64.
(Reading database ... 215016 files and directories currently installed.)
Preparing to unpack .../00-libtcl8.6_8.6.13+dfsg-2_amd64.deb ...
Unpacking libtcl8.6:amd64 (8.6.13+dfsg-2) ...
Selecting previously unselected package libtk8.6:amd64.
Preparing to unpack .../01-libtk8.6_8.6.13-2_amd64.deb ...
Unpacking libtk8.6:amd64 (8.6.13-2) ...
Selecting previously unselected package tk8.6-blt2.5.
Preparing to unpack .../02-tk8.6-blt2.5_2.5.3+dfsg-4.1_amd64.deb ...
Unpacking tk8.6-blt2.5 (2.5.3+dfsg-4.1) ...
Selecting previously unselected package blt.
Preparing to unpack .../03-blt_2.5.3+dfsg-4.1_amd64.deb ...
Unpacking blt (2.5.3+dfsg-4.1) ...
Selecting previously unselected package fonts-lyx.
Preparing to unpack .../04-fonts-lyx_2.3.7-1_all.deb ...
Unpacking fonts-lyx (2.3.7-1) ...
Selecting previously unselected package python3-backcall.
Preparing to unpack .../05-python3-backcall_0.2.0-4_all.deb ...
Unpacking python3-backcall (0.2.0-4) ...
Selecting previously unselected package python3-decorator.
Preparing to unpack .../06-python3-decorator_5.1.1-3_all.deb ...
Unpacking python3-decorator (5.1.1-3) ...
Selecting previously unselected package python3-parso.
Preparing to unpack .../07-python3-parso_0.8.3-1_all.deb ...
Unpacking python3-parso (0.8.3-1) ...
Selecting previously unselected package python3-jedi.
Preparing to unpack .../08-python3-jedi_0.18.2-1_all.deb ...
Unpacking python3-jedi (0.18.2-1) ...
Selecting previously unselected package python3-traitlets.
Preparing to unpack .../09-python3-traitlets_5.5.0-1_all.deb ...
Unpacking python3-traitlets (5.5.0-1) ...
Selecting previously unselected package python3-matplotlib-inline.
Preparing to unpack .../10-python3-matplotlib-inline_0.1.6-2_all.deb ...
Unpacking python3-matplotlib-inline (0.1.6-2) ...
Selecting previously unselected package python3-ptyprocess.
Preparing to unpack .../11-python3-ptyprocess_0.7.0-5_all.deb ...
Unpacking python3-ptyprocess (0.7.0-5) ...
Selecting previously unselected package python3-pexpect.
Preparing to unpack .../12-python3-pexpect_4.8.0-4_all.deb ...
Unpacking python3-pexpect (4.8.0-4) ...
Selecting previously unselected package python3-pickleshare.
Preparing to unpack .../13-python3-pickleshare_0.7.5-5_all.deb ...
Unpacking python3-pickleshare (0.7.5-5) ...
Selecting previously unselected package python3-wcwidth.
Preparing to unpack .../14-python3-wcwidth_0.2.5+dfsg1-1.1_all.deb ...
Unpacking python3-wcwidth (0.2.5+dfsg1-1.1) ...
Selecting previously unselected package python3-prompt-toolkit.
Preparing to unpack .../15-python3-prompt-toolkit_3.0.36-2_all.deb ...
Unpacking python3-prompt-toolkit (3.0.36-2) ...
Selecting previously unselected package python3-pygments.
Preparing to unpack .../16-python3-pygments_2.14.0+dfsg-1_all.deb ...
Unpacking python3-pygments (2.14.0+dfsg-1) ...
Selecting previously unselected package python3-asttokens.
Preparing to unpack .../17-python3-asttokens_2.2.1-1_all.deb ...
Unpacking python3-asttokens (2.2.1-1) ...
Selecting previously unselected package python3-executing.
Preparing to unpack .../18-python3-executing_1.2.0-2_all.deb ...
Unpacking python3-executing (1.2.0-2) ...
Selecting previously unselected package python3-pure-eval.
Preparing to unpack .../19-python3-pure-eval_0.2.2-1_all.deb ...
Unpacking python3-pure-eval (0.2.2-1) ...
Selecting previously unselected package python3-stack-data.
Preparing to unpack .../20-python3-stack-data_0.6.2-3_all.deb ...
Unpacking python3-stack-data (0.6.2-3) ...
Selecting previously unselected package python3-ipython.
Preparing to unpack .../21-python3-ipython_8.5.0-4_all.deb ...
Unpacking python3-ipython (8.5.0-4) ...
Selecting previously unselected package ipython3.
Preparing to unpack .../22-ipython3_8.5.0-4_all.deb ...
Unpacking ipython3 (8.5.0-4) ...
Selecting previously unselected package isympy-common.
Preparing to unpack .../23-isympy-common_1.11.1-1_all.deb ...
Unpacking isympy-common (1.11.1-1) ...
Selecting previously unselected package python3-mpmath.
Preparing to unpack .../24-python3-mpmath_1.2.1-2_all.deb ...
Unpacking python3-mpmath (1.2.1-2) ...
Selecting previously unselected package python3-sympy.
Preparing to unpack .../25-python3-sympy_1.11.1-1_all.deb ...
Unpacking python3-sympy (1.11.1-1) ...
Selecting previously unselected package isympy3.
Preparing to unpack .../26-isympy3_1.11.1-1_all.deb ...
Unpacking isympy3 (1.11.1-1) ...
Selecting previously unselected package libboost1.74-dev:amd64.
Preparing to unpack .../27-libboost1.74-dev_1.74.0+ds1-21_amd64.deb ...
Unpacking libboost1.74-dev:amd64 (1.74.0+ds1-21) ...
Selecting previously unselected package libboost-dev:amd64.
Preparing to unpack .../28-libboost-dev_1.74.0.3_amd64.deb ...
Unpacking libboost-dev:amd64 (1.74.0.3) ...
Selecting previously unselected package libimagequant0:amd64.
Preparing to unpack .../29-libimagequant0_2.17.0-1_amd64.deb ...
Unpacking libimagequant0:amd64 (2.17.0-1) ...
Selecting previously unselected package libjs-jquery-ui.
Preparing to unpack .../30-libjs-jquery-ui_1.13.2+dfsg-1_all.deb ...
Unpacking libjs-jquery-ui (1.13.2+dfsg-1) ...
Selecting previously unselected package libopenblas0-pthread:amd64.
Preparing to unpack .../31-libopenblas0-pthread_0.3.21+ds-4_amd64.deb ...
Unpacking libopenblas0-pthread:amd64 (0.3.21+ds-4) ...
Selecting previously unselected package liblbfgsb0:amd64.
Preparing to unpack .../32-liblbfgsb0_3.0+dfsg.4-1_amd64.deb ...
Unpacking liblbfgsb0:amd64 (3.0+dfsg.4-1) ...
Selecting previously unselected package libopenblas0:amd64.
Preparing to unpack .../33-libopenblas0_0.3.21+ds-4_amd64.deb ...
Unpacking libopenblas0:amd64 (0.3.21+ds-4) ...
Selecting previously unselected package libopenblas-pthread-dev:amd64.
Preparing to unpack .../34-libopenblas-pthread-dev_0.3.21+ds-4_amd64.deb ...
Unpacking libopenblas-pthread-dev:amd64 (0.3.21+ds-4) ...
Selecting previously unselected package libopenblas-dev:amd64.
Preparing to unpack .../35-libopenblas-dev_0.3.21+ds-4_amd64.deb ...
Unpacking libopenblas-dev:amd64 (0.3.21+ds-4) ...
Selecting previously unselected package libpython3-all-dev:amd64.
Preparing to unpack .../36-libpython3-all-dev_3.11.2-1+b1_amd64.deb ...
Unpacking libpython3-all-dev:amd64 (3.11.2-1+b1) ...
Selecting previously unselected package libqhull-r8.0:amd64.
Preparing to unpack .../37-libqhull-r8.0_2020.2-5_amd64.deb ...
Unpacking libqhull-r8.0:amd64 (2020.2-5) ...
Selecting previously unselected package libraqm0:amd64.
Preparing to unpack .../38-libraqm0_0.7.0-4.1_amd64.deb ...
Unpacking libraqm0:amd64 (0.7.0-4.1) ...
Selecting previously unselected package libxsimd-dev:amd64.
Preparing to unpack .../39-libxsimd-dev_8.1.0-7_amd64.deb ...
Unpacking libxsimd-dev:amd64 (8.1.0-7) ...
Selecting previously unselected package python-matplotlib-data.
Preparing to unpack .../40-python-matplotlib-data_3.6.3-1_all.deb ...
Unpacking python-matplotlib-data (3.6.3-1) ...
Selecting previously unselected package python3-all.
Preparing to unpack .../41-python3-all_3.11.2-1+b1_amd64.deb ...
Unpacking python3-all (3.11.2-1+b1) ...
Selecting previously unselected package python3-all-dev.
Preparing to unpack .../42-python3-all-dev_3.11.2-1+b1_amd64.deb ...
Unpacking python3-all-dev (3.11.2-1+b1) ...
Selecting previously unselected package python3-appdirs.
Preparing to unpack .../43-python3-appdirs_1.4.4-3_all.deb ...
Unpacking python3-appdirs (1.4.4-3) ...
Selecting previously unselected package python3-attr.
Preparing to unpack .../44-python3-attr_22.2.0-1_all.deb ...
Unpacking python3-attr (22.2.0-1) ...
Selecting previously unselected package python3-gast.
Preparing to unpack .../45-python3-gast_0.5.2-2_all.deb ...
Unpacking python3-gast (0.5.2-2) ...
Selecting previously unselected package python3-beniget.
Preparing to unpack .../46-python3-beniget_0.4.1-3_all.deb ...
Unpacking python3-beniget (0.4.1-3) ...
Selecting previously unselected package python3-soupsieve.
Preparing to unpack .../47-python3-soupsieve_2.3.2-1_all.deb ...
Unpacking python3-soupsieve (2.3.2-1) ...
Selecting previously unselected package python3-bs4.
Preparing to unpack .../48-python3-bs4_4.11.2-2_all.deb ...
Unpacking python3-bs4 (4.11.2-2) ...
Selecting previously unselected package python3-numpy.
Preparing to unpack .../49-python3-numpy_1%3a1.24.2-1+deb12u1_amd64.deb ...
Unpacking python3-numpy (1:1.24.2-1+deb12u1) ...
Selecting previously unselected package python3-contourpy.
Preparing to unpack .../50-python3-contourpy_1.0.7-1+b1_amd64.deb ...
Unpacking python3-contourpy (1.0.7-1+b1) ...
Selecting previously unselected package python3-cycler.
Preparing to unpack .../51-python3-cycler_0.11.0-1_all.deb ...
Unpacking python3-cycler (0.11.0-1) ...
Selecting previously unselected package python3-pythran.
Preparing to unpack .../52-python3-pythran_0.11.0+ds-7_amd64.deb ...
Unpacking python3-pythran (0.11.0+ds-7) ...
Selecting previously unselected package python3-scipy.
Preparing to unpack .../53-python3-scipy_1.10.1-2_amd64.deb ...
Unpacking python3-scipy (1.10.1-2) ...
Selecting previously unselected package python3-ufolib2.
Preparing to unpack .../54-python3-ufolib2_0.14.0+dfsg1-1_all.deb ...
Unpacking python3-ufolib2 (0.14.0+dfsg1-1) ...
Selecting previously unselected package python3-tz.
Preparing to unpack .../55-python3-tz_2022.7.1-4_all.deb ...
Unpacking python3-tz (2022.7.1-4) ...
Selecting previously unselected package python3-fs.
Preparing to unpack .../56-python3-fs_2.4.16-2_all.deb ...
Unpacking python3-fs (2.4.16-2) ...
Selecting previously unselected package python3-lxml:amd64.
Preparing to unpack .../57-python3-lxml_4.9.2-1+b1_amd64.deb ...
Unpacking python3-lxml:amd64 (4.9.2-1+b1) ...
Selecting previously unselected package python3-lz4.
Preparing to unpack .../58-python3-lz4_4.0.2+dfsg-1+b2_amd64.deb ...
Unpacking python3-lz4 (4.0.2+dfsg-1+b2) ...
Selecting previously unselected package unicode-data.
Preparing to unpack .../59-unicode-data_15.0.0-1_all.deb ...
Unpacking unicode-data (15.0.0-1) ...
Selecting previously unselected package python3-fonttools.
Preparing to unpack .../60-python3-fonttools_4.38.0-1+b1_amd64.deb ...
Unpacking python3-fonttools (4.38.0-1+b1) ...
Selecting previously unselected package python3-webencodings.
Preparing to unpack .../61-python3-webencodings_0.5.1-5_all.deb ...
Unpacking python3-webencodings (0.5.1-5) ...
Selecting previously unselected package python3-html5lib.
Preparing to unpack .../62-python3-html5lib_1.1-3_all.deb ...
Unpacking python3-html5lib (1.1-3) ...
Selecting previously unselected package python3-kiwisolver.
Preparing to unpack .../63-python3-kiwisolver_1.4.4-1+b1_amd64.deb ...
Unpacking python3-kiwisolver (1.4.4-1+b1) ...
Selecting previously unselected package python3-pil:amd64.
Preparing to unpack .../64-python3-pil_9.4.0-1.1+deb12u1_amd64.deb ...
Unpacking python3-pil:amd64 (9.4.0-1.1+deb12u1) ...
Selecting previously unselected package python3-tk:amd64.
Preparing to unpack .../65-python3-tk_3.11.2-3_amd64.deb ...
Unpacking python3-tk:amd64 (3.11.2-3) ...
Selecting previously unselected package python3-pil.imagetk:amd64.
Preparing to unpack .../66-python3-pil.imagetk_9.4.0-1.1+deb12u1_amd64.deb ...
Unpacking python3-pil.imagetk:amd64 (9.4.0-1.1+deb12u1) ...
Selecting previously unselected package python3-packaging.
Preparing to unpack .../67-python3-packaging_23.0-1_all.deb ...
Unpacking python3-packaging (23.0-1) ...
Selecting previously unselected package python3-matplotlib.
Preparing to unpack .../68-python3-matplotlib_3.6.3-1+b1_amd64.deb ...
Unpacking python3-matplotlib (3.6.3-1+b1) ...
Selecting previously unselected package python3-olefile.
Preparing to unpack .../69-python3-olefile_0.46-3_all.deb ...
Unpacking python3-olefile (0.46-3) ...
Selecting previously unselected package python3-scapy.
Preparing to unpack .../70-python3-scapy_2.5.0+dfsg-2_all.deb ...
Unpacking python3-scapy (2.5.0+dfsg-2) ...
Setting up python3-attr (22.2.0-1) ...
Setting up python3-pure-eval (0.2.2-1) ...
Setting up libboost1.74-dev:amd64 (1.74.0+ds1-21) ...
Setting up libopenblas0-pthread:amd64 (0.3.21+ds-4) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 to provide /usr/lib/x86_64-linux-gnu/libblas.so.3 (libblas.so.3-x86_64-linux-gnu) in auto mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3 to provide /usr/lib/x86_64-linux-gnu/liblapack.so.3 (liblapack.so.3-x86_64-linux-gnu) in auto mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so.0 to provide /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (libopenblas.so.0-x86_64-linux-gnu) in auto mode
Setting up python3-backcall (0.2.0-4) ...
Setting up python3-parso (0.8.3-1) ...
Setting up python3-lz4 (4.0.2+dfsg-1+b2) ...
Setting up python3-asttokens (2.2.1-1) ...
Setting up fonts-lyx (2.3.7-1) ...
Setting up python3-olefile (0.46-3) ...
Setting up isympy-common (1.11.1-1) ...
Setting up python3-gast (0.5.2-2) ...
Setting up libqhull-r8.0:amd64 (2020.2-5) ...
Setting up python3-all (3.11.2-1+b1) ...
Setting up python3-webencodings (0.5.1-5) ...
Setting up python3-tz (2022.7.1-4) ...
Setting up unicode-data (15.0.0-1) ...
Setting up python3-beniget (0.4.1-3) ...
Setting up libxsimd-dev:amd64 (8.1.0-7) ...
Setting up python3-decorator (5.1.1-3) ...
Setting up python3-pygments (2.14.0+dfsg-1) ...
Setting up python3-packaging (23.0-1) ...
Setting up libjs-jquery-ui (1.13.2+dfsg-1) ...
Setting up python3-wcwidth (0.2.5+dfsg1-1.1) ...
Setting up python3-executing (1.2.0-2) ...
Setting up libpython3-all-dev:amd64 (3.11.2-1+b1) ...
Setting up libraqm0:amd64 (0.7.0-4.1) ...
Setting up python3-cycler (0.11.0-1) ...
Setting up libimagequant0:amd64 (2.17.0-1) ...
Setting up python3-kiwisolver (1.4.4-1+b1) ...
Setting up libtcl8.6:amd64 (8.6.13+dfsg-2) ...
Setting up python3-html5lib (1.1-3) ...
Setting up python3-numpy (1:1.24.2-1+deb12u1) ...
Setting up python3-pickleshare (0.7.5-5) ...
Setting up python3-scapy (2.5.0+dfsg-2) ...
Setting up libopenblas0:amd64 (0.3.21+ds-4) ...
Setting up python3-lxml:amd64 (4.9.2-1+b1) ...
Setting up python3-traitlets (5.5.0-1) ...
Setting up python3-contourpy (1.0.7-1+b1) ...
Setting up libboost-dev:amd64 (1.74.0.3) ...
Setting up python3-mpmath (1.2.1-2) ...
Setting up python-matplotlib-data (3.6.3-1) ...
Setting up python3-appdirs (1.4.4-3) ...
Setting up python3-stack-data (0.6.2-3) ...
Setting up python3-soupsieve (2.3.2-1) ...
Setting up liblbfgsb0:amd64 (3.0+dfsg.4-1) ...
Setting up python3-ptyprocess (0.7.0-5) ...
Setting up python3-prompt-toolkit (3.0.36-2) ...
Setting up libopenblas-pthread-dev:amd64 (0.3.21+ds-4) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so to provide /usr/lib/x86_64-linux-gnu/libblas.so (libblas.so-x86_64-linux-gnu) in auto mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so to provide /usr/lib/x86_64-linux-gnu/liblapack.so (liblapack.so-x86_64-linux-gnu) in auto mode
update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so to provide /usr/lib/x86_64-linux-gnu/libopenblas.so (libopenblas.so-x86_64-linux-gnu) in auto mode
Setting up python3-all-dev (3.11.2-1+b1) ...
Setting up python3-sympy (1.11.1-1) ...
Setting up python3-jedi (0.18.2-1) ...
Setting up libtk8.6:amd64 (8.6.13-2) ...
Setting up python3-bs4 (4.11.2-2) ...
Setting up python3-matplotlib-inline (0.1.6-2) ...
Setting up python3-fs (2.4.16-2) ...
Setting up python3-pil:amd64 (9.4.0-1.1+deb12u1) ...
Setting up libopenblas-dev:amd64 (0.3.21+ds-4) ...
Setting up python3-pexpect (4.8.0-4) ...
Setting up python3-pythran (0.11.0+ds-7) ...
Setting up tk8.6-blt2.5 (2.5.3+dfsg-4.1) ...
Setting up python3-scipy (1.10.1-2) ...
Setting up blt (2.5.3+dfsg-4.1) ...
Setting up python3-tk:amd64 (3.11.2-3) ...
Setting up python3-pil.imagetk:amd64 (9.4.0-1.1+deb12u1) ...
Setting up python3-ipython (8.5.0-4) ...
Setting up ipython3 (8.5.0-4) ...
Processing triggers for libc-bin (2.36-9+deb12u8) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for menu (2.1.49) ...
Processing triggers for fontconfig (2.14.1-4) ...
Setting up python3-fonttools (4.38.0-1+b1) ...
Setting up isympy3 (1.11.1-1) ...
Setting up python3-ufolib2 (0.14.0+dfsg1-1) ...
Setting up python3-matplotlib (3.6.3-1+b1) ...
(venv) root@debian12:~/my_udp_monitor# sudo apt install pipx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fonts-font-awesome fonts-lato ghp-import libjs-bootstrap4 libjs-highlight.js libjs-lunr
  libjs-modernizr libjs-popper.js libjs-sizzle mkdocs node-jquery python-babel-localedata
  python3-argcomplete python3-babel python3-click python3-colorama python3-iniconfig
  python3-jinja2 python3-joblib python3-livereload python3-lunr python3-markdown
  python3-mergedeep python3-more-itertools python3-nltk python3-pluggy python3-psutil
  python3-py python3-pyinotify python3-pytest python3-pyyaml-env-tag python3-regex
  python3-simplejson python3-tornado python3-tqdm python3-userpath python3-watchdog
  python3-yaml sphinx-rtd-theme-common
Suggested packages:
  libjs-es5-shim mkdocs-doc nodejs python-jinja2-doc coffeescript node-less node-uglify
  python-livereload-doc python3-django python3-flask python3-slimmer python-lunr-doc
  python-markdown-doc python-psutil-doc subversion python-pyinotify-doc
  python-tornado-doc python3-twisted
Recommended packages:
  prover9
The following NEW packages will be installed:
  fonts-font-awesome fonts-lato ghp-import libjs-bootstrap4 libjs-highlight.js libjs-lunr
  libjs-modernizr libjs-popper.js libjs-sizzle mkdocs node-jquery pipx
  python-babel-localedata python3-argcomplete python3-babel python3-click
  python3-colorama python3-iniconfig python3-jinja2 python3-joblib python3-livereload
  python3-lunr python3-markdown python3-mergedeep python3-more-itertools python3-nltk
  python3-pluggy python3-psutil python3-py python3-pyinotify python3-pytest
  python3-pyyaml-env-tag python3-regex python3-simplejson python3-tornado python3-tqdm
  python3-userpath python3-watchdog python3-yaml sphinx-rtd-theme-common
0 upgraded, 40 newly installed, 0 to remove and 3 not upgraded.
Need to get 17.1 MB of archives.
After this operation, 74.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian bookworm/main amd64 fonts-lato all 2.0-2.1 [2,696 kB]
Ign:1 http://deb.debian.org/debian bookworm/main amd64 fonts-lato all 2.0-2.1             
Get:2 http://deb.debian.org/debian bookworm/main amd64 fonts-font-awesome all 5.0.10+really4.7.0~dfsg-4.1 [517 kB]
Ign:2 http://deb.debian.org/debian bookworm/main amd64 fonts-font-awesome all 5.0.10+really4.7.0~dfsg-4.1
Get:3 http://deb.debian.org/debian bookworm/main amd64 ghp-import all 2.1.0-3 [12.3 kB]   
Get:4 http://deb.debian.org/debian bookworm/main amd64 libjs-popper.js all 1.16.1+ds-6 [52.4 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libjs-bootstrap4 all 4.6.1+dfsg1-4 [517 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 libjs-highlight.js all 9.18.5+dfsg1-2 [397 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 libjs-lunr all 2.3.9~dfsg-2 [76.6 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 libjs-modernizr all 2.6.2+ds1-5 [47.1 kB]
Get:9 http://deb.debian.org/debian bookworm/main amd64 libjs-sizzle all 2.3.6+ds+~2.3.3-2 [31.6 kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 python3-tornado amd64 6.2.0-3 [337 kB]
Get:11 http://deb.debian.org/debian bookworm/main amd64 python3-livereload all 2.6.3-2 [26.4 kB]
Get:12 http://deb.debian.org/debian bookworm/main amd64 python3-colorama all 0.4.6-2 [36.8 kB]
Get:13 http://deb.debian.org/debian bookworm/main amd64 python3-click all 8.1.3-2 [92.2 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 python3-joblib all 1.2.0-4 [211 kB]
Get:15 http://deb.debian.org/debian bookworm/main amd64 python3-regex amd64 0.1.20221031-1+b1 [266 kB]
Get:16 http://deb.debian.org/debian bookworm/main amd64 python3-tqdm all 4.64.1-1 [97.7 kB]
Get:17 http://deb.debian.org/debian bookworm/main amd64 python3-nltk all 3.8-1 [1,004 kB] 
Get:18 http://deb.debian.org/debian bookworm/main amd64 python3-lunr all 0.6.2-2 [29.1 kB]
Get:19 http://deb.debian.org/debian bookworm/main amd64 sphinx-rtd-theme-common all 1.2.0+dfsg-1 [997 kB]
Get:20 http://deb.debian.org/debian bookworm/main amd64 python3-jinja2 all 3.1.2-1 [119 kB]
Get:21 http://deb.debian.org/debian bookworm/main amd64 python3-markdown all 3.4.1-2 [64.7 kB]
Get:22 http://deb.debian.org/debian bookworm/main amd64 python3-mergedeep all 1.3.4-3 [6,556 B]
Get:23 http://deb.debian.org/debian bookworm/main amd64 python3-yaml amd64 6.0-3+b2 [119 kB]
Get:24 http://deb.debian.org/debian bookworm/main amd64 python3-pyyaml-env-tag all 0.1-3 [5,252 B]
Get:25 http://deb.debian.org/debian bookworm/main amd64 python3-watchdog all 2.2.1-1 [124 kB]
Get:26 http://deb.debian.org/debian bookworm/main amd64 mkdocs all 1.4.2+dfsg-2 [2,252 kB]
Get:27 http://deb.debian.org/debian bookworm/main amd64 node-jquery all 3.6.1+dfsg+~3.5.14-1 [160 kB]
Get:28 http://deb.debian.org/debian bookworm/main amd64 python3-argcomplete all 2.0.0-1 [34.7 kB]
Get:29 http://deb.debian.org/debian bookworm/main amd64 python3-userpath all 1.8.0-1 [10.6 kB]
Get:30 http://deb.debian.org/debian bookworm/main amd64 pipx all 1.1.0-1 [393 kB]         
Get:31 http://deb.debian.org/debian bookworm/main amd64 python-babel-localedata all 2.10.3-1 [5,615 kB]
Get:32 http://deb.debian.org/debian bookworm/main amd64 python3-babel all 2.10.3-1 [103 kB]
Get:33 http://deb.debian.org/debian bookworm/main amd64 python3-iniconfig all 1.1.1-2 [6,396 B]
Get:34 http://deb.debian.org/debian bookworm/main amd64 python3-more-itertools all 8.10.0-2 [53.0 kB]
Get:35 http://deb.debian.org/debian bookworm/main amd64 python3-pluggy all 1.0.0+repack-1 [19.7 kB]
Get:36 http://deb.debian.org/debian bookworm/main amd64 python3-psutil amd64 5.9.4-1+b1 [189 kB]
Get:37 http://deb.debian.org/debian bookworm/main amd64 python3-py all 1.11.0-1 [89.2 kB] 
Get:38 http://deb.debian.org/debian bookworm/main amd64 python3-pyinotify all 0.9.6-2 [27.4 kB]
Get:39 http://deb.debian.org/debian bookworm/main amd64 python3-pytest all 7.2.1-2 [236 kB]
Get:40 http://deb.debian.org/debian bookworm/main amd64 python3-simplejson amd64 3.18.3-1 [59.8 kB]
Get:1 http://deb.debian.org/debian bookworm/main amd64 fonts-lato all 2.0-2.1 [2,696 kB]  
Get:2 http://deb.debian.org/debian bookworm/main amd64 fonts-font-awesome all 5.0.10+really4.7.0~dfsg-4.1 [517 kB]
Fetched 17.0 MB in 10min 30s (27.1 kB/s)                                                  
Extracting templates from packages: 100%
Selecting previously unselected package fonts-lato.
(Reading database ... 242894 files and directories currently installed.)
Preparing to unpack .../00-fonts-lato_2.0-2.1_all.deb ...
Unpacking fonts-lato (2.0-2.1) ...
Selecting previously unselected package fonts-font-awesome.
Preparing to unpack .../01-fonts-font-awesome_5.0.10+really4.7.0~dfsg-4.1_all.deb ...
Unpacking fonts-font-awesome (5.0.10+really4.7.0~dfsg-4.1) ...
Selecting previously unselected package ghp-import.
Preparing to unpack .../02-ghp-import_2.1.0-3_all.deb ...
Unpacking ghp-import (2.1.0-3) ...
Selecting previously unselected package libjs-popper.js.
Preparing to unpack .../03-libjs-popper.js_1.16.1+ds-6_all.deb ...
Unpacking libjs-popper.js (1.16.1+ds-6) ...
Selecting previously unselected package libjs-bootstrap4.
Preparing to unpack .../04-libjs-bootstrap4_4.6.1+dfsg1-4_all.deb ...
Unpacking libjs-bootstrap4 (4.6.1+dfsg1-4) ...
Selecting previously unselected package libjs-highlight.js.
Preparing to unpack .../05-libjs-highlight.js_9.18.5+dfsg1-2_all.deb ...
Unpacking libjs-highlight.js (9.18.5+dfsg1-2) ...
Selecting previously unselected package libjs-lunr.
Preparing to unpack .../06-libjs-lunr_2.3.9~dfsg-2_all.deb ...
Unpacking libjs-lunr (2.3.9~dfsg-2) ...
Selecting previously unselected package libjs-modernizr.
Preparing to unpack .../07-libjs-modernizr_2.6.2+ds1-5_all.deb ...
Unpacking libjs-modernizr (2.6.2+ds1-5) ...
Selecting previously unselected package libjs-sizzle.
Preparing to unpack .../08-libjs-sizzle_2.3.6+ds+~2.3.3-2_all.deb ...
Unpacking libjs-sizzle (2.3.6+ds+~2.3.3-2) ...
Selecting previously unselected package python3-tornado.
Preparing to unpack .../09-python3-tornado_6.2.0-3_amd64.deb ...
Unpacking python3-tornado (6.2.0-3) ...
Selecting previously unselected package python3-livereload.
Preparing to unpack .../10-python3-livereload_2.6.3-2_all.deb ...
Unpacking python3-livereload (2.6.3-2) ...
Selecting previously unselected package python3-colorama.
Preparing to unpack .../11-python3-colorama_0.4.6-2_all.deb ...
Unpacking python3-colorama (0.4.6-2) ...
Selecting previously unselected package python3-click.
Preparing to unpack .../12-python3-click_8.1.3-2_all.deb ...
Unpacking python3-click (8.1.3-2) ...
Selecting previously unselected package python3-joblib.
Preparing to unpack .../13-python3-joblib_1.2.0-4_all.deb ...
Unpacking python3-joblib (1.2.0-4) ...
Selecting previously unselected package python3-regex.
Preparing to unpack .../14-python3-regex_0.1.20221031-1+b1_amd64.deb ...
Unpacking python3-regex (0.1.20221031-1+b1) ...
Selecting previously unselected package python3-tqdm.
Preparing to unpack .../15-python3-tqdm_4.64.1-1_all.deb ...
Unpacking python3-tqdm (4.64.1-1) ...
Selecting previously unselected package python3-nltk.
Preparing to unpack .../16-python3-nltk_3.8-1_all.deb ...
Unpacking python3-nltk (3.8-1) ...
Selecting previously unselected package python3-lunr.
Preparing to unpack .../17-python3-lunr_0.6.2-2_all.deb ...
Unpacking python3-lunr (0.6.2-2) ...
Selecting previously unselected package sphinx-rtd-theme-common.
Preparing to unpack .../18-sphinx-rtd-theme-common_1.2.0+dfsg-1_all.deb ...
Unpacking sphinx-rtd-theme-common (1.2.0+dfsg-1) ...
Selecting previously unselected package python3-jinja2.
Preparing to unpack .../19-python3-jinja2_3.1.2-1_all.deb ...
Unpacking python3-jinja2 (3.1.2-1) ...
Selecting previously unselected package python3-markdown.
Preparing to unpack .../20-python3-markdown_3.4.1-2_all.deb ...
Unpacking python3-markdown (3.4.1-2) ...
Selecting previously unselected package python3-mergedeep.
Preparing to unpack .../21-python3-mergedeep_1.3.4-3_all.deb ...
Unpacking python3-mergedeep (1.3.4-3) ...
Selecting previously unselected package python3-yaml.
Preparing to unpack .../22-python3-yaml_6.0-3+b2_amd64.deb ...
Unpacking python3-yaml (6.0-3+b2) ...
Selecting previously unselected package python3-pyyaml-env-tag.
Preparing to unpack .../23-python3-pyyaml-env-tag_0.1-3_all.deb ...
Unpacking python3-pyyaml-env-tag (0.1-3) ...
Selecting previously unselected package python3-watchdog.
Preparing to unpack .../24-python3-watchdog_2.2.1-1_all.deb ...
Unpacking python3-watchdog (2.2.1-1) ...
Selecting previously unselected package mkdocs.
Preparing to unpack .../25-mkdocs_1.4.2+dfsg-2_all.deb ...
Unpacking mkdocs (1.4.2+dfsg-2) ...
Selecting previously unselected package node-jquery.
Preparing to unpack .../26-node-jquery_3.6.1+dfsg+~3.5.14-1_all.deb ...
Unpacking node-jquery (3.6.1+dfsg+~3.5.14-1) ...
Selecting previously unselected package python3-argcomplete.
Preparing to unpack .../27-python3-argcomplete_2.0.0-1_all.deb ...
Unpacking python3-argcomplete (2.0.0-1) ...
Selecting previously unselected package python3-userpath.
Preparing to unpack .../28-python3-userpath_1.8.0-1_all.deb ...
Unpacking python3-userpath (1.8.0-1) ...
Selecting previously unselected package pipx.
Preparing to unpack .../29-pipx_1.1.0-1_all.deb ...
Unpacking pipx (1.1.0-1) ...
Selecting previously unselected package python-babel-localedata.
Preparing to unpack .../30-python-babel-localedata_2.10.3-1_all.deb ...
Unpacking python-babel-localedata (2.10.3-1) ...
Selecting previously unselected package python3-babel.
Preparing to unpack .../31-python3-babel_2.10.3-1_all.deb ...
Unpacking python3-babel (2.10.3-1) ...
Selecting previously unselected package python3-iniconfig.
Preparing to unpack .../32-python3-iniconfig_1.1.1-2_all.deb ...
Unpacking python3-iniconfig (1.1.1-2) ...
Selecting previously unselected package python3-more-itertools.
Preparing to unpack .../33-python3-more-itertools_8.10.0-2_all.deb ...
Unpacking python3-more-itertools (8.10.0-2) ...
Selecting previously unselected package python3-pluggy.
Preparing to unpack .../34-python3-pluggy_1.0.0+repack-1_all.deb ...
Unpacking python3-pluggy (1.0.0+repack-1) ...
Selecting previously unselected package python3-psutil.
Preparing to unpack .../35-python3-psutil_5.9.4-1+b1_amd64.deb ...
Unpacking python3-psutil (5.9.4-1+b1) ...
Selecting previously unselected package python3-py.
Preparing to unpack .../36-python3-py_1.11.0-1_all.deb ...
Unpacking python3-py (1.11.0-1) ...
Selecting previously unselected package python3-pyinotify.
Preparing to unpack .../37-python3-pyinotify_0.9.6-2_all.deb ...
Unpacking python3-pyinotify (0.9.6-2) ...
Selecting previously unselected package python3-pytest.
Preparing to unpack .../38-python3-pytest_7.2.1-2_all.deb ...
Unpacking python3-pytest (7.2.1-2) ...
Selecting previously unselected package python3-simplejson.
Preparing to unpack .../39-python3-simplejson_3.18.3-1_amd64.deb ...
Unpacking python3-simplejson (3.18.3-1) ...
Setting up python3-more-itertools (8.10.0-2) ...
Setting up python3-iniconfig (1.1.1-2) ...
Setting up python3-tornado (6.2.0-3) ...
Setting up fonts-lato (2.0-2.1) ...
Setting up python3-py (1.11.0-1) ...
Setting up python3-joblib (1.2.0-4) ...
Setting up libjs-popper.js (1.16.1+ds-6) ...
Setting up python3-colorama (0.4.6-2) ...
Setting up libjs-lunr (2.3.9~dfsg-2) ...
Setting up python3-pyinotify (0.9.6-2) ...
Setting up python3-tqdm (4.64.1-1) ...
Setting up python3-yaml (6.0-3+b2) ...
Setting up python3-click (8.1.3-2) ...
Setting up libjs-sizzle (2.3.6+ds+~2.3.3-2) ...
Setting up libjs-modernizr (2.6.2+ds1-5) ...
Setting up python3-psutil (5.9.4-1+b1) ...
Setting up python-babel-localedata (2.10.3-1) ...
Setting up python3-pyyaml-env-tag (0.1-3) ...
Setting up python3-simplejson (3.18.3-1) ...
Setting up python3-jinja2 (3.1.2-1) ...
Setting up python3-markdown (3.4.1-2) ...
Setting up python3-mergedeep (1.3.4-3) ...
Setting up python3-regex (0.1.20221031-1+b1) ...
Setting up python3-pluggy (1.0.0+repack-1) ...
Setting up libjs-highlight.js (9.18.5+dfsg1-2) ...
Setting up ghp-import (2.1.0-3) ...
Setting up python3-livereload (2.6.3-2) ...
Setting up libjs-bootstrap4 (4.6.1+dfsg1-4) ...
Setting up python3-argcomplete (2.0.0-1) ...
Setting up python3-nltk (3.8-1) ...
Setting up fonts-font-awesome (5.0.10+really4.7.0~dfsg-4.1) ...
Setting up sphinx-rtd-theme-common (1.2.0+dfsg-1) ...
Setting up node-jquery (3.6.1+dfsg+~3.5.14-1) ...
Setting up python3-userpath (1.8.0-1) ...
Setting up python3-lunr (0.6.2-2) ...
Setting up python3-babel (2.10.3-1) ...
update-alternatives: using /usr/bin/pybabel-python3 to provide /usr/bin/pybabel (pybabel) in auto mode
Setting up python3-pytest (7.2.1-2) ...
Setting up python3-watchdog (2.2.1-1) ...
Setting up pipx (1.1.0-1) ...
Setting up mkdocs (1.4.2+dfsg-2) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for fontconfig (2.14.1-4) ...
(venv) root@debian12:~/my_udp_monitor# pipx install scapy
⚠️  Note: scapy was already on your PATH at /root/my_udp_monitor/venv/bin/scapy
  installed package scapy 2.6.0, installed using Python 3.11.2
  These apps are now globally available
    - scapy
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will
    not be globally accessible until your PATH is updated. Run `pipx ensurepath` to
    automatically add it, or manually modify your PATH in your shell's config file (i.e.
    ~/.bashrc).
done! ✨ 🌟 ✨
(venv) root@debian12:~/my_udp_monitor# 